AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iot-button

  Sample SAM Template for iot-button

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  SlackApiToken:
    Type: String
    Description: Slack API Token
  SlackChannel:
    Type: String
    Description: Slack Channel

Resources:
  NotifyOutOfStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notify_out_of_stock/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64
      Environment:
        Variables:
          SLACK_API_TOKEN: !Ref SlackApiToken
          SLACK_CHANNEL: !Ref SlackChannel
      Events:
        IoT:
          Type: IoTRule
          Properties:
            Sql: SELECT * FROM 'iot-button'

Outputs:
  NotifyOutOfStockFunction:
    Description: "Notify Out of Stock Lambda Function ARN"
    Value: !GetAtt NotifyOutOfStockFunction.Arn
  NotifyOutOfStockFunctionIamRole:
    Description: "Implicit IAM Role created for Notify Out of Stock function"
    Value: !GetAtt NotifyOutOfStockFunction.Arn
